<?php
/*                                                                       *
* This script is part of the epoq Recommendation Service project         *
*                                                                        *
* TypoGento is free software; you can redistribute it and/or modify it   *
* under the terms of the GNU General Public License version 2 as         *
* published by the Free Software Foundation.                             *
*                                                                        *
* This script is distributed in the hope that it will be useful, but     *
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-    *
* TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General      *
* Public License for more details.                                       *
*                                                                        *
* @version $Id: cart.phtml 487 2010-08-05 12:32:57Z weller $
* @license http://opensource.org/licenses/gpl-license.php GNU Public License, version 2
*/
?>

<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="crosssell">
    <div class="head"><h4><?php echo $this->__('epoq: You may also be interested in the following product(s)') ?></h4></div>
    <ul id="crosssell-products-list">
    <?php $this->resetItemsIterator() ?>
    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
        <?php if($_link=$this->getIterableItem()): ?>
            <li class="item">
                <a class="product-image" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <div class="product-details">
                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
                    <?php echo $this->getPriceHtml($_link, true) ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_link) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_link)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php endif; ?>
    <?php endfor; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
    
</div>
<script type="text/javascript">
$$('a.epoq-recommendation-link').each(function(elem, index){
	var newParam = 'recommendation_id=<?php echo $this->getSession()->getLastRecommendationId();?>',
	params = '?' + newParam;
    params = elem.href.replace(new RegExp('[\?&]' + 'recommendation_id' + '[^&]*'), '$1' + newParam);
    if (params === elem.href) {
        if(elem.href.indexOf('?') == '-1'){
    		params += '?' + newParam;
        }else{
        	params += '&' + newParam;
        }
    }
    elem.href = params;
});
</script>
<?php endif ?>
